class IngredientData {
  // 1. The map you provided (can be constant)
  static const Map<String, int> ingredientPopularityMap = {
    'Acini Di Pepe': 20,
    'Acorn Squash': 55,
    'Active Dry Yeast': 80,
    'Adobo Seasoning': 45,
    'Adobo Sauce': 30,
    'Adzuki Beans': 25,
    'Agave Nectar': 45,
    'Ahi Tuna': 45,
    'Alfalfa Sprouts': 35,
    'All-Purpose Flour': 100,
    'Almond Butter': 45,
    'Almond Extract': 35,
    'Almond Meal': 40,
    'Almond Milk': 50,
    'Almond Paste': 30,
    'Amaranth Flour': 20,
    'Amarena Cherries': 25,
    'Amaretto': 15,
    'Amber Rum': 25,
    'Amontillado Sherry': 20,
    'Ancho Chile': 30,
    'Anchovy Fillets': 40,
    'Andouille Sausage': 35,
    'Angel Hair Pasta': 45,
    'Angostura Bitters': 30,
    'Anise Extract': 25,
    'Anise Seed': 30,
    'Anjou Pears': 40,
    'Annatto Seeds': 20,
    'Apple Brandy': 25,
    'Apple Butter': 45,
    'Apple Cider Vinegar': 55,
    'Apple Cider': 45,
    'Apple Juice': 45,
    'Apple Pie Spice': 25,
    'Apricot Halves': 40,
    'Apricot Jam': 35,
    'Apricot Jelly': 30,
    'Apricot Nectar': 35,
    'Arborio Rice': 50,
    'Arctic Char': 35,
    'Arepa Flour': 30,
    'Arrowroot Powder': 30,
    'Artichoke Hearts': 45,
    'Artichoke Paste': 25,
    'Ascorbic Acid': 15,
    'Asparagus': 55,
    'Avocado Oil': 35,
    'Baby Back Ribs': 40,
    'Baby Bok Choy': 40,
    'Baby Carrots': 45,
    'Baby Spinach': 55,
    'Baby Potatoes': 50,
    'Back Ribs': 40,
    'Bacon Fat': 45,
    'Bagel Chips': 20,
    'Baking Apples': 45,
    'Baking Chocolate': 45,
    'Baking Potatoes': 45,
    'Baking Powder': 95,
    'Baking Soda': 95,
    'Balsamic Vinegar': 55,
    'Bamboo Shoots': 40,
    'Banana Leaves': 35,
    'Banana Peppers': 45,
    'Barbecue Sauce': 35,
    'Barramundi': 25,
    'Basil Leaves': 55,
    'Basmati Rice': 55,
    'Bay Leaf': 55,
    'Bay Scallops': 35,
    'Bean Threads': 25,
    'Beef Base': 35,
    'Beef Bones': 35,
    'Beef Bouillon': 40,
    'Beef Brisket': 45,
    'Beef Broth': 55,
    'Beef Consomme': 30,
    'Beef Demi-Glace': 25,
    'Beef Drippings': 30,
    'Beef Fillet': 45,
    'Beef For Stew': 45,
    'Beef Gravy': 40,
    'Beef Jerky': 30,
    'Beef Marrow': 30,
    'Beef Rib Roast': 45,
    'Beef Ribs': 45,
    'Beef Roast': 45,
    'Beef Round': 45,
    'Beef Shank': 40,
    'Beef Shin': 40,
    'Beef Shoulder': 40,
    'Beef Sirloin': 45,
    'Beef Steak': 50,
    'Beef Stew Meat': 45,
    'Beef Stock': 55,
    'Beef Tenderloin': 45,
    'Beefsteak Tomatoes': 45,
    'Beet Greens': 50,
    'Beet Juice': 50,
    'Beetroot Puree': 35,
    'Bell Pepper': 50,
    'Berry Preserve': 35,
    'Bibb Lettuce': 50,
    'Bicarbonate Of Soda': 50,
    'Bing Cherries': 50,
    'Bitter Melon': 50,
    'Bitter Orange Preserve': 35,
    'Bittersweet Baking Chocolate': 50,
    'Bittersweet Chocolate': 50,
    'Black Bass': 50,
    'Black Beans': 50,
    'Black Cardamom Pod': 20,
    'Black Cardamom Pods': 50,
    'Black Cherries': 50,
    'Black Cod Fillets': 50,
    'Black Cod': 50,
    'Black Forest Ham': 50,
    'Black Garlic': 50,
    'Black Grapes': 50,
    'Black Mission Figs': 50,
    'Black Mushrooms': 50,
    'Black Olive Oil': 20,
    'Black Olive Paste': 35,
    'Black Olive Spread': 20,
    'Black Olive': 20,
    'Black Olives': 50,
    'Black Pepper Powder': 20,
    'Black Pepper': 95,
    'Black Peppercorn': 20,
    'Black Peppercorns': 50,
    'Black Pudding': 20,
    'Black Rice Vinegar': 50,
    'Black Rice': 50,
    'Black Sea Bass': 50,
    'Black Sesame Oil': 35,
    'Black Tahini Paste': 35,
    'Black Tea Extract': 20,
    'Black Tea Leaves': 50,
    'Black Tea Liqueur': 20,
    'Black Tea Powder': 20,
    'Black Tea': 50,
    'Black Treacle': 50,
    'Black Turtle Beans': 50,
    'Black Vinegar': 50,
    'Black Walnut': 50,
    'Black-Eyed Peas': 50,
    'Blackening Seasoning': 50,
    'Blackstrap Molasses': 50,
    'Blade Steak': 50,
    'Blanched Almonds': 50,
    'Blanched Hazelnuts': 50,
    'Bleu Cheese Dressing': 35,
    'Blood Orange Juice': 50,
    'Blood Orange Liqueur': 20,
    'Blood Orange': 50,
    'Blue Cheese Dressing': 50,
    'Blue Cheese': 50,
    'Blue Crabs': 50,
    'Blueberry Pie Filling': 50,
    'Blueberry Preserve': 35,
    'Bock Beer': 50,
    'Bok Choy': 50,
    'Bologna Sausage': 35,
    'Bombay Duck': 35,
    'Bone In': 50,
    'Bone-In Chicken Breasts': 50,
    'Bone-In Chicken': 50,
    'Bone-In Pork Chops': 50,
    'Bone-In Short Ribs': 50,
    'Boneless Beef Roast': 50,
    'Boneless Chicken Breast': 50,
    'Boneless Chicken Thighs': 50,
    'Boneless Chicken': 50,
    'Boneless Chops': 50,
    'Boneless Chuck Roast': 50,
    'Boneless Duck Breast': 50,
    'Boneless Ham': 50,
    'Boneless Lamb': 50,
    'Boneless Pork Loin': 50,
    'Boneless Pork Shoulder': 50,
    'Boneless Pork Tenderloin': 50,
    'Boneless Salmon Fillets': 50,
    'Boneless Sirloin Steak': 50,
    'Boneless Sirloin': 50,
    'Boneless Skinless Chicken': 50,
    'Boneless Turkey Breast': 50,
    'Bonito Flakes': 50,
    'Borlotti Beans': 50,
    'Bottled Clam Juice': 50,
    'Bottled Lemon Juice': 35,
    'Bottled Lime Juice': 50,
    'Bottled Marinara Sauce': 35,
    'Bottled Salsa': 35,
    'Bottled Water': 35,
    'Bottom Round Roast': 50,
    'Bottom Round': 50,
    'Bouillon Cube': 50,
    'Bouquet Garni': 50,
    'Bourbon Brandy': 20,
    'Bourbon Liqueur': 20,
    'Bourbon Rum': 20,
    'Bourbon Whiskey': 50,
    'Bow-Tie Pasta': 50,
    'Boysenberry Preserve': 35,
    'Bran Flakes': 50,
    'Branzino Fillets': 50,
    'Brazil Nut Oil': 35,
    'Bread Crumbs': 35,
    'Bread Flour': 50,
    'Bread Rolls': 50,
    'Bread Slices': 50,
    'Breadcrumb': 20,
    'Breakfast Sausage Links': 50,
    'Breakfast Sausages': 50,
    'Brewed Coffee': 50,
    'Brewed Espresso': 50,
    'Brewed Tea': 50,
    'Brie Cheese': 50,
    'Brine-Cured Black Olives': 50,
    'Brine-Cured Olives': 50,
    'Brioche Bread': 50,
    'Brioche Buns': 50,
    'Broad Beans': 50,
    'Broccoli Florets': 50,
    'Broccoli Rabe': 50,
    'Broccoli Slaw': 50,
    'Broccoli Stems': 50,
    'Brown Ale': 50,
    'Brown Basmati Rice': 50,
    'Brown Beech Mushrooms': 50,
    'Brown Butter': 50,
    'Brown Chicken Stock': 50,
    'Brown Gravy': 50,
    'Brown Lentils': 50,
    'Brown Mustard': 50,
    'Brown Rice Flour': 20,
    'Brown Rice Syrup': 20,
    'Brown Rice Vinegar': 50,
    'Brown Rice': 50,
    'Brown Sugar Syrup': 20,
    'Brown Sugar': 50,
    'Brownie Mix': 35,
    'Brussels Sprouts': 50,
    'Buckwheat Groats': 50,
    'Buckwheat Honey': 50,
    'Buckwheat Noodles': 50,
    'Buckwheat Soba Noodles': 50,
    'Buffalo Mozzarella': 50,
    'Bulb Fennel': 50,
    'Bulgogi Sauce': 35,
    'Bulgur Wheat': 50,
    'Burger Buns': 50,
    'Burger Rolls': 50,
    'Burrata Cheese': 35,
    'Butter Beans': 50,
    'Butter Cake': 50,
    'Butter Crackers': 50,
    'Butter Extract': 35,
    'Butter Flavor Shortening': 50,
    'Butter Lettuce': 50,
    'Butter Rum': 20,
    'Butter Sauce': 20,
    'Butter Whiskey': 20,
    'Buttercream Frosting': 50,
    'Buttercup Squash': 50,
    'Buttermilk Biscuits': 50,
    'Buttermilk Cornbread': 50,
    'Buttermilk Extract': 20,
    'Buttermilk Powder': 20,
    'Butternut Squash': 50,
    'Butterscotch Extract': 35,
    'Button Mushrooms': 50,
    'Cabbage Head': 50,
    'Cabbage Leaves': 50,
    'Cabbage Powder': 20,
    'Cabernet Sauvignon': 50,
    'Cacao Nibs': 50,
    'Cactus Paddles': 50,
    'Cajun Spice Mix': 20,
    'Cajun Spice': 35,
    'Cake Flour': 35,
    'Cake Yeast': 50,
    'Calamata Olives': 50,
    'Calimyrna Figs': 50,
    'Candied Cherries': 50,
    'Candied Fruit': 50,
    'Candied Ginger': 50,
    'Candied Lemon Peel': 50,
    'Candied Orange Peel': 50,
    'Candied Peel': 50,
    'Candied Pineapple': 50,
    'Candy Bar': 50,
    'Candy Canes': 50,
    'Candy Sprinkles': 50,
    'Cane Sugar': 50,
    'Cane Vinegar': 50,
    'Canned Beans': 50,
    'Canned Beef Broth': 50,
    'Canned Black Beans': 50,
    'Canned Chicken Broth': 50,
    'Canned Chicken': 50,
    'Canned Chipotles': 50,
    'Canned Chopped Tomatoes': 50,
    'Canned Coconut Milk': 50,
    'Canned Corn Kernels': 35,
    'Canned Corn': 50,
    'Canned Fruit Cocktail': 35,
    'Canned Green Chiles': 35,
    'Canned Jalapeno Peppers': 50,
    'Canned Mushrooms': 35,
    'Canned Peas': 35,
    'Canned Pumpkin Puree': 35,
    'Canned Refried Beans': 35,
    'Canned Salmon': 50,
    'Canned Tomatoes': 50,
    'Canned Tuna': 50,
    'Canned Whole Tomatoes': 35,
    'Cannellini Beans': 50,
    'Cannelloni Shells': 50,
    'Cannoli Shells': 50,
    'Canola Mayonnaise': 50,
    'Cantaloupe': 35,
    'Caper Berries': 50,
    'Caper Sauce': 35,
    'Capsicum': 35,
    'Cara Cara Orange': 50,
    'Caramel Extract': 20,
    'Caramel Ice Cream': 50,
    'Caramel Liqueur': 20,
    'Caramel Powder': 20,
    'Caramel Sauce': 35,
    'Caramel Syrup': 20,
    'Caramel Topping': 50,
    'Caraway Seed': 35,
    'Carbonated Water': 50,
    'Cardamom Extract': 20,
    'Cardamom Pods': 50,
    'Cardamom Powder': 20,
    'Cardamom Seed': 35,
    'Carnaroli Rice': 50,
    'Carne Asada': 50,
    'Carob Extract': 20,
    'Carob Liqueur': 20,
    'Carob Powder': 35,
    'Carrot Greens': 50,
    'Carrot Juice': 50,
    'Carrot Powder': 20,
    'Carrot Sticks': 50,
    'Cashew Butter': 50,
    'Cashew Milk': 50,
    'Cashew Nuts': 50,
    'Cashew Oil': 35,
    'Cassava Flour': 35,
    'Cassia Cinnamon': 50,
    'Caster Sugar': 50,
    'Catfish Fillets': 50,
    'Catfish': 35,
    'Caul Fat': 50,
    'Cauliflower Florets': 50,
    'Cavolo Nero': 50,
    'Cayenne Pepper': 50,
    'Celery Heart': 50,
    'Celery Leaves': 50,
    'Celery Ribs': 50,
    'Celery Root': 50,
    'Celery Salt': 50,
    'Celery Seed': 35,
    'Celery Stick': 50,
    'Celery Tops': 50,
    'Center Cut Bacon': 50,
    'Center-Cut Salmon Fillet': 50,
    'Cereal Flakes': 50,
    'Chaat Masala': 50,
    'Chai Tea Bags': 35,
    'Chai Tea Concentrate': 50,
    'Chambord Liqueur': 35,
    'Champagne Grapes': 50,
    'Champagne Vinegar': 50,
    'Channa Dal': 50,
    'Chantilly Cream': 35,
    'Char Fillets': 50,
    'Cheddar Cheese Powder': 20,
    'Cheddar Cheese Soup': 50,
    'Cheddar Cheese': 50,
    'Cheese Curds': 50,
    'Cheese Dip': 50,
    'Cheese Ravioli': 50,
    'Cheese Slices': 50,
    'Cheese Soup': 50,
    'Cheese Sticks': 50,
    'Cheese Tortellini': 50,
    'Cherry Brandy': 20,
    'Cherry Extract': 20,
    'Cherry Gelatin': 50,
    'Cherry Juice': 50,
    'Cherry Liqueur': 35,
    'Cherry Peppers': 50,
    'Cherry Pie Filling': 50,
    'Cherry Powder': 20,
    'Cherry Preserve': 35,
    'Cherry Tomatoes': 50,
    'Cherrystone Clams': 50,
    'Chestnut Flour': 35,
    'Chicken And Beef Broth': 20,
    'Chicken And Beef Stock': 20,
    'Chicken Base Powder': 20,
    'Chicken Base': 50,
    'Chicken Bones': 50,
    'Chicken Bouillon Granules': 50,
    'Chicken Bouillon Powder': 20,
    'Chicken Bouillon': 50,
    'Chicken Breast Fillets': 50,
    'Chicken Breast Halves': 50,
    'Chicken Breast Strips': 50,
    'Chicken Breast Tenderloins': 50,
    'Chicken Breast Tenders': 50,
    'Chicken Breasts': 50,
    'Chicken Broth': 50,
    'Chicken Carcass': 50,
    'Chicken Chili': 20,
    'Chicken Cutlets': 50,
    'Chicken Demi-Glace': 50,
    'Chicken Fingers': 50,
    'Chicken Glaze': 20,
    'Chicken Gravy Mix': 35,
    'Chicken Gravy': 50,
    'Chicken In Water': 50,
    'Chicken Leg Quarters': 50,
    'Chicken Legs': 50,
    'Chicken Liqueur': 20,
    'Chicken Livers': 50,
    'Chicken Meat': 50,
    'Chicken Noodle Soup Mix': 35,
    'Chicken Noodle Soup': 35,
    'Chicken Parts': 50,
    'Chicken Paste': 20,
    'Chicken Pieces': 50,
    'Chicken Rub': 20,
    'Chicken Salad': 50,
    'Chicken Sauce': 20,
    'Chicken Sausage': 50,
    'Chicken Soup Base': 50,
    'Chicken Stock': 50,
    'Chicken Strips': 50,
    'Chicken Thigh Fillets': 35,
    'Chicken Thigh': 35,
    'Chicken Thighs': 50,
    'Chicken Wingettes': 50,
    'Chicken Wings': 50,
    'Chicken-Apple Sausage': 50,
    'Chickpea Flour': 35,
    'Chili Bean Paste': 35,
    'Chili Bean Sauce': 35,
    'Chili Paste': 35,
    'Chili Pepper': 35,
    'Chili Powder': 20,
    'Chili Sauce': 35,
    'Chili Spice Mix': 35,
    'Chili Spice': 35,
    'Chili-Garlic Paste': 35,
    'Chilled Prosecco': 50,
    'Chilled Seltzer': 50,
    'Chinese Five-Spice Powder': 35,
    'Chinese Sausage': 35,
    'Chipotle Extract': 20,
    'Chipotle Peppers': 50,
    'Chipotle Powder': 20,
    'Chipotle Salsa': 50,
    'Chipotle Sauce': 20,
    'Chipotle Spice': 20,
    'Chipotles In Adobo': 50,
    'Chive Blossoms': 50,
    'Chocolate Baking Bar': 50,
    'Chocolate Bars': 50,
    'Chocolate Candy Bars': 50,
    'Chocolate Candy': 50,
    'Chocolate Chunks': 50,
    'Chocolate Curls': 50,
    'Chocolate Extract': 20,
    'Chocolate Frosting': 50,
    'Chocolate Graham Crackers': 50,
    'Chocolate Hazelnut Spread': 35,
    'Chocolate Ice Cream': 50,
    'Chocolate Instant Pudding': 50,
    'Chocolate Liqueur': 20,
    'Chocolate Milk': 50,
    'Chocolate Morsels': 50,
    'Chocolate Mousse': 50,
    'Chocolate Powder': 20,
    'Chocolate Sandwich Cookies': 50,
    'Chocolate Sauce': 20,
    'Chocolate Shavings': 50,
    'Chocolate Sprinkles': 50,
    'Chocolate Syrup': 20,
    'Chocolate Wafer Cookies': 50,
    'Chopped Almonds': 50,
    'Chopped Bacon': 50,
    'Chopped Bell Pepper': 50,
    'Chopped Celery': 50,
    'Chopped Cilantro': 50,
    'Chopped Cooked Meat': 50,
    'Chopped Fresh Chives': 50,
    'Chopped Fresh Herbs': 50,
    'Chopped Fresh Mint': 50,
    'Chopped Fresh Sage': 50,
    'Chopped Fresh Thyme': 50,
    'Chopped Garlic': 50,
    'Chopped Ham': 50,
    'Chopped Hazelnuts': 50,
    'Chopped Leaves': 50,
    'Chopped Nuts': 50,
    'Chopped Onion': 50,
    'Chopped Parsley': 50,
    'Chopped Pecans': 50,
    'Chopped Tomatoes': 50,
    'Chopped Walnuts': 50,
    'Chorizo Sausage': 50,
    'Chow Mein Noodles': 50,
    'Chuck Roast': 50,
    'Chuck Short Ribs': 50,
    'Chunky Peanut Butter': 50,
    'Chunky Salsa': 50,
    'Ciabatta Buns': 50,
    'Ciabatta Loaf': 50,
    'Ciabatta Rolls': 50,
    'Cider Brandy': 20,
    'Cider Liqueur': 20,
    'Cider Vinegar': 50,
    'Cilantro Leaves': 50,
    'Cilantro Root': 50,
    'Cilantro Seed': 35,
    'Cilantro Sprigs': 50,
    'Cilantro Stems': 50,
    'Cinnamon Extract': 20,
    'Cinnamon Graham Crackers': 50,
    'Cinnamon Liqueur': 20,
    'Cinnamon Powder': 20,
    'Cinnamon Rolls': 50,
    'Cinnamon Sauce': 20,
    'Cinnamon Stick': 35,
    'Cinnamon Sticks': 50,
    'Cinnamon Sugar': 50,
    'Cipollini Onions': 50,
    'Citric Acid': 50,
    'Citrus Fruit': 50,
    'Citrus Juice': 50,
    'Citrus Peel': 50,
    'Clam Juice': 50,
    'Clarified Butter': 50,
    'Clear Honey': 50,
    'Clementine Juice': 50,
    'Clotted Cream': 50,
    'Clove Extract': 20,
    'Clove Liqueur': 20,
    'Clove Oil': 35,
    'Clove Powder': 20,
    'Clove Seed': 35,
    'Clover Honey': 50,
    'Club Soda': 50,
    'Coarse Ground Mustard': 50,
    'Coarse Kosher Salt': 50,
    'Coarse Salt': 50,
    'Coarse Sea Salt': 50,
    'Coarse Sugar': 50,
    'Cocktail Pumpernickel Bread': 50,
    'Cocoa Butter': 20,
    'Cocoa Extract': 20,
    'Cocoa Liqueur': 20,
    'Cocoa Nibs': 35,
    'Cocoa Powder': 35,
    'Cocoa Sauce': 20,
    'Coconut Butter': 50,
    'Coconut Cream': 50,
    'Coconut Flakes': 50,
    'Coconut Juice': 50,
    'Coconut Milk': 50,
    'Coconut Sugar': 50,
    'Coconut Water': 50,
    'Cod Cheeks': 50,
    'Cod Fillets': 50,
    'Cod Fish': 50,
    'Coffee Beans': 50,
    'Coffee Extract': 20,
    'Coffee Granules': 50,
    'Coffee Ice Cream': 50,
    'Coffee Liqueur': 35,
    'Coffee Powder': 20,
    'Coffee Sauce': 20,
    'Coffee Syrup': 35,
    'Cognac Brandy': 35,
    'Cognac Liqueur': 20,
    'Cognac Rum': 20,
    'Cognac Whiskey': 20,
    'Cola Extract': 20,
    'Cola Liqueur': 20,
    'Cola Powder': 20,
    'Cola Sauce': 20,
    'Cola Syrup': 35,
    'Cola-Flavored Carbonated Beverage': 50,
    'Cold Coffee': 50,
    'Cold Meatloaf': 50,
    'Cold Milk': 50,
    'Cold Water': 50,
    'Coleslaw Dressing': 50,
    'Collard Green Leaves': 50,
    'Collard Greens': 50,
    'Condensed Chicken Broth': 50,
    'Condensed Cream Of Mushroom Soup': 35,
    'Condensed Cream Of Tomato Soup': 35,
    'Condensed Cream': 50,
    'Condensed Milk': 50,
    'Condensed Mushroom Soup': 35,
    'Condensed Soup': 50,
    'Condensed Tomato Soup': 50,
    'Confectioners Sugar': 50,
    'Converted Rice': 50,
    'Cooked Bacon': 50,
    'Cooked Barley': 50,
    'Cooked Brisket': 50,
    'Cooked Brown Rice': 50,
    'Cooked Chicken Breasts': 50,
    'Cooked Chicken': 50,
    'Cooked Deli Ham': 50,
    'Cooked Ham': 50,
    'Cooked Meat': 50,
    'Cooked Meatballs': 50,
    'Cooked Pumpkin': 50,
    'Cooked Rice': 50,
    'Cooked Shrimp': 50,
    'Cooked Steak': 50,
    'Cooked Turkey': 50,
    'Cooked Vegetables': 50,
    'Cooked White Rice': 50,
    'Cookie Dough': 35,
    'Cookie Pie Crust': 35,
    'Cooking Apples': 50,
    'Cooking Liquid': 50,
    'Cooking Sherry': 50,
    'Cooking Spray': 50,
    'Cooking Wine': 35,
    'Cool Whip': 50,
    'Coriander Extract': 20,
    'Coriander Powder': 20,
    'Coriander Seed': 35,
    'Corkscrew Pasta': 50,
    'Corn Flakes': 50,
    'Corn Flour': 35,
    'Corn Grits': 50,
    'Corn Husks': 50,
    'Corn Kernels': 50,
    'Corn Muffin': 50,
    'Corn Niblets': 50,
    'Corn Salsa': 50,
    'Corn Starch': 50,
    'Corn Syrup': 35,
    'Corn Tortillas': 50,
    'Corned Beef': 50,
    'Cornflake Cereal': 50,
    'Cornish Hens': 50,
    'Cottage Cheese': 50,
    'Country Bread': 50,
    'Country Ham': 50,
    'Country Loaf': 50,
    'Country Style Bread': 50,
    'Country White Bread': 50,
    'Couscous': 35,
    'Crab Cakes': 35,
    'Crab Claws': 50,
    'Crab Meat': 50,
    'Crab Sticks': 50,
    'Cracked Black Pepper': 50,
    'Cracked Wheat': 50,
    'Cracker Meal': 50,
    'Cranberry Beans': 50,
    'Cranberry Juice Cocktail': 50,
    'Cranberry Juice': 50,
    'Cranberry Sauce': 35,
    'Cream Cheese Frosting': 50,
    'Cream Cheese': 50,
    'Cream Of Broccoli Soup': 35,
    'Cream Of Celery Soup': 35,
    'Cream Of Chicken Soup': 35,
    'Cream Of Coconut': 50,
    'Cream Of Mushroom Soup': 35,
    'Cream Of Onion Soup': 35,
    'Cream Of Potato Soup': 35,
    'Cream Of Shrimp Soup': 35,
    'Cream Of Spinach Soup': 35,
    'Cream Of Tartar': 50,
    'Cream Of Tomato Soup': 35,
    'Cream Of Vegetable Soup': 35,
    'Cream Sherry': 50,
    'Cream Yogurt': 50,
    'Creamed Spinach': 50,
    'Creamer Potatoes': 50,
    'Creamy Peanut Butter': 50,
    'Creme De Cacao': 50,
    'Creme De Cassis Liqueur': 35,
    'Cremini Mushrooms': 50,
    'Creole Mustard': 50,
    'Creole Seasoning': 50,
    'Creole Spice Mix': 20,
    'Crispy Bacon': 50,
    'Crispy Rice Cereal': 50,
    'Crock Pot Roast': 35,
    'Crumbs': 35,
    'Crushed Cornflakes': 50,
    'Crushed Garlic': 50,
    'Crushed Graham Crackers': 50,
    'Crushed Ice': 50,
    'Crushed Peppermint Candy': 50,
    'Crushed Pineapple': 50,
    'Crushed Pistachio': 50,
    'Crushed Pretzels': 50,
    'Crushed Red Pepper Flakes': 35,
    'Crushed Red Pepper': 50,
    'Crushed Saltines': 50,
    'Crushed Tomatoes': 50,
    'Crusty Bread': 50,
    'Crusty Loaf': 50,
    'Crusty Rolls': 50,
    'Crusty Sandwich Rolls': 50,
    'Crystallized Ginger': 50,
    'Cubanelle Pepper': 35,
    'Cube Steaks': 50,
    'Cubed Beef': 50,
    'Cubed Bread': 50,
    'Cubed Ham': 50,
    'Cubed Mango': 50,
    'Cubed Potatoes': 50,
    'Cultured Buttermilk': 50,
    'Cumin Extract': 20,
    'Cumin Powder': 20,
    'Cumin Seed': 35,
    'Curacao Brandy': 20,
    'Curacao Liqueur': 35,
    'Cured Chorizo': 50,
    'Cured Meats': 50,
    'Cured Pork': 50,
    'Curing Salt': 50,
    'Curly Endive': 50,
    'Curly Kale': 50,
    'Curly Parsley': 50,
    'Curry Extract': 20,
    'Curry Leaf': 50,
    'Curry Leaves': 50,
    'Curry Powder': 35,
    'Curry Sauce': 20,
    'Curry': 35,
    'Cut Up Chicken': 50,
    'Daikon Sprouts': 50,
    'Dairy-Free Milk': 35,
    'Dandelion Greens': 50,
    'Dark Ale': 50,
    'Dark Beer': 50,
    'Dark Brown Sugar': 50,
    'Dark Chicken Stock': 50,
    'Dark Chocolate': 50,
    'Dark Lager': 50,
    'Dark Leafy Greens': 50,
    'Dark Meat': 50,
    'Dark Molasses': 50,
    'Dark Muscovado Sugar': 50,
    'Dark Rum': 35,
    'Dark Soy Sauce': 35,
    'Dark Soy': 50,
    'Dark Turkey Meat': 50,
    'Dashi Kombu': 50,
    'Day Old Bread': 50,
    'Decorating Sugars': 50,
    'Deli Ham': 50,
    'Deli Meat': 35,
    'Deli Rolls': 50,
    'Delicata Squash': 50,
    'Demerara Sugar': 50,
    'Demi Baguette': 50,
    'Dessert Wine': 35,
    'Deveined Shrimp': 50,
    'Diced Apples': 50,
    'Diced Bacon': 50,
    'Diced Bell Pepper': 50,
    'Diced Celery': 50,
    'Diced Chicken': 50,
    'Diced Ham': 50,
    'Diced Mushrooms': 50,
    'Diced Onions': 50,
    'Diced Pimentos': 50,
    'Diced Potatoes': 50,
    'Diced Red Onions': 50,
    'Diced Tomatoes': 50,
    'Diced Yellow Onion': 50,
    'Dijon Mustard': 50,
    'Dill Extract': 20,
    'Dill Pickles': 50,
    'Dill Powder': 20,
    'Dill Seed': 35,
    'Dill Weed': 50,
    'Dinner Rolls': 50,
    'Dinosaur Kale': 50,
    'Distilled Vinegar': 50,
    'Ditalini Pasta': 50,
    'Double Crust': 50,
    'Dragon Fruit': 50,
    'Dried Ancho Chile': 35,
    'Dried Apple Rings': 50,
    'Dried Apple': 50,
    'Dried Apricot': 50,
    'Dried Basil': 50,
    'Dried Beans': 50,
    'Dried Black Beans': 50,
    'Dried Black Fungus': 35,
    'Dried Bonito Flakes': 50,
    'Dried Chickpea': 35,
    'Dried Chickpeas': 50,
    'Dried Chili Flakes': 20,
    'Dried Chili Powder': 20,
    'Dried Chili Sauce': 20,
    'Dried Chili Spice Mix': 20,
    'Dried Chili': 20,
    'Dried Chipotle Pepper': 50,
    'Dried Chives': 50,
    'Dried Coconut Flakes': 50,
    'Dried Corn Husks': 35,
    'Dried Cranberries': 50,
    'Dried Cumin': 20,
    'Dried Currants': 50,
    'Dried Dates': 50,
    'Dried Dill': 50,
    'Dried Fenugreek Leaves': 35,
    'Dried Fettuccine': 50,
    'Dried Fish Roe': 20,
    'Dried Fruit': 50,
    'Dried Garlic': 20,
    'Dried Ginger Powder': 20,
    'Dried Ginger': 20,
    'Dried Green Chili Flakes': 20,
    'Dried Ground Chili Flakes': 20,
    'Dried Ground Chili Powder': 20,
    'Dried Ground Chili Sauce': 20,
    'Dried Ground Chili Spice Mix': 20,
    'Dried Ground Chili': 20,
    'Dried Ground Cumin': 20,
    'Dried Ground Ginger Powder': 20,
    'Dried Ground Ginger': 20,
    'Dried Ground Nutmeg': 20,
    'Dried Ground Paprika': 20,
    'Dried Ground Turmeric Powder': 20,
    'Dried Ground Turmeric': 20,
    'Dried Herb': 20,
    'Dried Horseradish': 20,
    'Dried Italian Herb': 20,
    'Dried Italian Herb Mix': 20,
    'Dried Italian Herb Powder': 20,
    'Dried Jasmine Tea': 20,
    'Dried Jasmine Tea Powder': 20,
    'Dried Juniper Berries': 20,
    'Dried Juniper Berry Extract': 20,
    'Dried Kaffir Lime Leaf': 20,
    'Dried Kaffir Lime Leaf Powder': 20,
    'Dried Kefir Lime Leaf': 20,
    'Dried Kefir Lime Leaf Powder': 20,
    'Dried Kelp': 50,
    'Dried Kidney Bean': 35,
    'Dried Kidney Beans': 50,
    'Dried Kombu': 20,
    'Dried Kombu Powder': 20,
    'Dried Lavender Flowers': 50,
    'Dried Lavender': 50,
    'Dried Lemon Balm': 20,
    'Dried Lemon Balm Powder': 20,
    'Dried Lemon Peel': 20,
    'Dried Lemon Peel Powder': 20,
    'Dried Lemongrass': 20,
    'Dried Lemongrass Powder': 20,
    'Dried Lentils': 50,
    'Dried Lime Extract': 20,
    'Dried Lime Leaf Extract': 20,
    'Dried Lime Leaf Oil': 20,
    'Dried Lime Leaf Powder': 20,
    'Dried Lime Leaf Rub': 20,
    'Dried Lime Leaf Sauce': 20,
    'Dried Lime Leaf Spice Mix': 20,
    'Dried Lime Leaf Spice': 20,
    'Dried Lime Leaf': 20,
    'Dried Lime Oil': 20,
    'Dried Lime Peel': 20,
    'Dried Lime Powder': 20,
    'Dried Lime': 20,
    'Dried Long Pepper': 20,
    'Dried Lotus Root': 20,
    'Dried Mace': 20,
    'Dried Madder Root': 20,
    'Dried Mango': 50,
    'Dried Marigold Flower': 20,
    'Dried Marjoram': 20,
    'Dried Minced Garlic': 50,
    'Dried Minced Onion': 50,
    'Dried Mint': 20,
    'Dried Mission Figs': 50,
    'Dried Morel Mushroom': 20,
    'Dried Mushroom': 20,
    'Dried Mushrooms': 50,
    'Dried Mustard': 20,
    'Dried Navy Bean': 35,
    'Dried Navy Beans': 50,
    'Dried Nutmeg': 20,
    'Dried Okra': 35,
    'Dried Onion Flakes': 35,
    'Dried Onion': 20,
    'Dried Orange Flower': 20,
    'Dried Orange Peel': 50,
    'Dried Orange': 20,
    'Dried Oregano': 50,
    'Dried Pappardelle': 50,
    'Dried Paprika': 20,
    'Dried Parsley': 50,
    'Dried Pasilla Chile': 20,
    'Dried Pasta': 50,
    'Dried Peppermint': 20,
    'Dried Pineapple': 50,
    'Dried Pink Peppercorn': 20,
    'Dried Pinto Bean': 35,
    'Dried Pinto Beans': 50,
    'Dried Porcini Mushroom': 20,
    'Dried Porcini Mushrooms': 50,
    'Dried Poultry Seasoning': 20,
    'Dried Quinoa': 20,
    'Dried Red Bean': 20,
    'Dried Red Chili': 20,
    'Dried Red Pepper': 20,
    'Dried Red Wine': 20,
    'Dried Rice Extract': 20,
    'Dried Rice Noodle': 20,
    'Dried Rice Noodles': 50,
    'Dried Rice': 20,
    'Dried Rigatoni': 50,
    'Dried Rosemary Leaves': 35,
    'Dried Rosemary': 50,
    'Dried Saffron': 35,
    'Dried Sage': 50,
    'Dried Seaweed': 35,
    'Dried Sesame Seed': 20,
    'Dried Shallot': 20,
    'Dried Shallots': 50,
    'Dried Shiitake Mushroom': 20,
    'Dried Shiitake Mushrooms': 50,
    'Dried Shredded Coconut': 35,
    'Dried Shrimp': 50,
    'Dried Smoked Paprika': 20,
    'Dried Soup Mix': 35,
    'Dried Soy Sauce': 20,
    'Dried Split Peas': 50,
    'Dried Star Anise': 20,
    'Dried Strawberries': 50,
    'Dried Tagliatelle': 50,
    'Dried Tamarind': 20,
    'Dried Tarragon Leaves': 50,
    'Dried Tarragon': 20,
    'Dried Tart Cherries': 50,
    'Dried Thyme Leaves': 35,
    'Dried Thyme': 50,
    'Dried Tomato': 20,
    'Dried Tomatoes': 50,
    'Dried Turmeric': 20,
    'Dried White Wine': 20,
    'Dried Whole Grain': 20,
    'Dried Whole Wheat Flour': 20,
    'Dried Whole Wheat Pasta': 20,
    'Dried Whole Wheat': 20,
    'Dried Wild Rice': 20,
    'Dried Wine': 20,
    'Dried Worcestershire Sauce': 20,
    'Dried Yeast': 20,
    'Dried Yellow Onion': 20,
    'Dried Yellow Pepper': 20,
    'Dried Yellow Rice': 20,
    'Dried Yellow Split Peas': 20,
    'Dried Zucchini': 20,
    'Dry Fettuccine': 50,
    'Dry Gin': 50,
    'Dry Hard Cider': 50,
    'Dry Mustard': 50,
    'Dry Roasted Peanuts': 50,
    'Dry Rub': 50,
    'Dry Sherry': 50,
    'Dry Vermouth': 50,
    'Dry Yeast': 50,
    'Duck Bones': 50,
    'Duck Breast Halves': 50,
    'Duck Breasts': 50,
    'Duck Confit': 35,
    'Duck Fat': 50,
    'Duck Glaze': 20,
    'Duck Liver': 50,
    'Duck Paste': 20,
    'Duck Rub': 20,
    'Duck Sauce': 20,
    'Duck Stock': 50,
    'Dulce De Leche': 50,
    'Dumpling Wrappers': 50,
    'Ear Of Corn': 50,
    'Easy Pizza Crust': 35,
    'Eating Apple': 50,
    'Eau De Vie': 50,
    'Edamame Beans': 50,
    'Edamame': 35,
    'Edible Flowers': 50,
    'Edible Glitter': 35,
    'Egg Beaters': 50,
    'Egg Bread': 50,
    'Egg Noodles': 50,
    'Egg Pasta': 50,
    'Egg Roll Skins': 50,
    'Egg Roll Wrappers': 50,
    'Egg Substitute': 50,
    'Egg Whites': 50,
    'Egg Yolks': 50,
    'Eggroll Wrappers': 50,
    'Elbow Macaroni': 50,
    'Elbow Pasta': 50,
    'Elderflower Liqueur': 35,
    'Empanada Wrappers': 50,
    'Energy Drink': 50,
    'Enriched White Rice': 50,
    'Espresso Beans': 50,
    'Espresso Powder': 35,
    'Evaporated Cane Juice': 50,
    'Evaporated Milk': 50,
    'Evaporated Skim Milk': 50,
    'Extra Firm Tofu': 50,
    'Extra Large Eggs': 50,
    'Extra Large Shrimp': 50,
    'Extra-Lean Ground Beef': 50,
    'Extract': 35,
    'Fajita Seasoning': 35,
    'Farmer Cheese': 50,
    'Fat Free Milk': 50,
    'Fat Free Yogurt': 50,
    'Fat-Free Chicken Broth': 50,
    'Fat-Free Cottage Cheese': 50,
    'Fat-Free Croutons': 50,
    'Fat-Free Mayonnaise': 50,
    'Fat-Free Milk': 35,
    'Fat-Free Refried Beans': 50,
    'Fava Beans': 50,
    'Fennel Bulb': 50,
    'Fennel Fronds': 50,
    'Fennel Pollen': 35,
    'Fenugreek Leaves': 50,
    'Fenugreek Seed': 35,
    'Fermented Black Beans': 50,
    'Feta Cheese': 50,
    'Fettuccine Alfredo': 35,
    'Fettuccine Pasta': 50,
    'Fiddlehead Ferns': 50,
    'Filet Mignon Steaks': 50,
    'Filet Mignon': 50,
    'Fillet Of Beef': 50,
    'Fillet Steaks': 50,
    'Fine Egg Noodles': 50,
    'Fine Granulated Sugar': 50,
    'Fine Salt': 50,
    'Fine Sea Salt': 50,
    'Finely Chopped Onion': 50,
    'Finely Ground Coffee': 50,
    'Fines Herbes': 50,
    'Fingerling Potatoes': 50,
    'Fino Sherry': 50,
    'Firm Silken Tofu': 50,
    'Firm Tofu': 50,
    'Fish Bones': 50,
    'Fish Broth': 50,
    'Fish Fillets': 50,
    'Fish Liqueur': 20,
    'Fish Paste': 20,
    'Fish Roe': 35,
    'Fish Rub': 20,
    'Fish Sauce': 20,
    'Fish Steaks': 50,
    'Fish Stock': 50,
    'Five Spice Powder': 20,
    'Five-Spice Powder': 35,
    'Flaked Coconut': 50,
    'Flank Steak': 50,
    'Flat Iron Steaks': 50,
    'Flat Leaf Parsley': 50,
    'Flavored Syrup': 35,
    'Flax Seed': 35,
    'Flax Seed Oil': 20,
    'Flax Seed Powder': 20,
    'Flax Seed Rub': 20,
    'Flax Seed Sauce': 20,
    'Flax Seed Vinegar': 20,
    'Flax Seed Wine': 20,
    'Flaxseed Oil': 35,
    'Flaxseed Powder': 20,
    'Flaxseed Rub': 20,
    'Flaxseed Sauce': 20,
    'Flaxseed Vinegar': 20,
    'Flaxseed Wine Extract': 20,
    'Flaxseed Wine Vinegar': 20,
    'Flaxseed Wine Wine Vinegar': 20,
    'Flaxseed Wine Wine': 20,
    'Flaxseed Wine': 20,
    'Fleur De Sel': 50,
    'Flounder Fillets': 50,
    'Flower Petals': 50,
    'Foie Gras': 50,
    'Fontina Cheese': 50,
    'Free-Range Chickens': 50,
    'Free-Range Eggs': 50,
    'Freeze-Dried Strawberries': 50,
    'French Fries': 50,
    'French Onion Soup Mix': 35,
    'Fresh Angel Hair': 50,
    'Fresh Asparagus': 50,
    'Fresh Basil Leaves': 50,
    'Fresh Basil': 50,
    'Fresh Bay Leaves': 50,
    'Fresh Bean': 50,
    'Fresh Blueberries': 50,
    'Fresh Cheese': 50,
    'Fresh Chervil': 50,
    'Fresh Chicken Stock': 50,
    'Fresh Chives': 50,
    'Fresh Chorizo': 50,
    'Fresh Cilantro': 50,
    'Fresh Cod': 50,
    'Fresh Coriander': 50,
    'Fresh Corn': 50,
    'Fresh Cranberries': 50,
    'Fresh Curry Leaves': 50,
    'Fresh Curry': 50,
    'Fresh Dill': 50,
    'Fresh Fish Roe': 35,
    'Fresh Flounder Fillets': 50,
    'Fresh Ginger Root': 50,
    'Fresh Ginger': 50,
    'Fresh Goat Cheese': 35,
    'Fresh Green Peas': 50,
    'Fresh Ham': 50,
    'Fresh Herbs': 50,
    'Fresh Horseradish': 35,
    'Fresh Lavender': 50,
    'Fresh Lemon Juice': 50,
    'Fresh Lemon': 50,
    'Fresh Lima Beans': 50,
    'Fresh Lime Juice': 50,
    'Fresh Lime': 50,
    'Fresh Marjoram': 50,
    'Fresh Masa': 50,
    'Fresh Mint': 50,
    'Fresh Mozzarella Balls': 50,
    'Fresh Mozzarella': 50,
    'Fresh Mushrooms': 50,
    'Fresh Onion': 50,
    'Fresh Orange Juice': 50,
    'Fresh Orange': 50,
    'Fresh Oregano Leaves': 50,
    'Fresh Oregano': 50,
    'Fresh Parsley Leaves': 50,
    'Fresh Parsley': 50,
    'Fresh Pasta': 50,
    'Fresh Peas': 50,
    'Fresh Pineapple': 50,
    'Fresh Poblano Pepper': 50,
    'Fresh Pork Fat': 50,
    'Fresh Raspberries': 50,
    'Fresh Rosemary': 50,
    'Fresh Sage': 50,
    'Fresh Salmon': 50,
    'Fresh Sea Bass': 50,
    'Fresh Shiitake Mushrooms': 50,
    'Fresh Spinach': 50,
    'Fresh Tarragon': 50,
    'Fresh Thyme Leaves': 50,
    'Fresh Thyme': 50,
    'Fresh Tomato Salsa': 50,
    'Fresh Tomatoes': 50,
    'Fresh Tuna Steaks': 50,
    'Fresh Turmeric': 50,
    'Fresh Udon': 50,
    'Fresh Yeast': 50,
    'Freshly Grated Parmesan': 50,
    'Freshly Ground Coffee': 35,
    'Freshly Ground Pepper': 50,
    'Fried Eggs': 50,
    'Fried Garlic': 50,
    'Fried Noodles': 35,
    'Fromage Blanc': 50,
    'Frozen Artichoke Hearts': 50,
    'Frozen Banana': 50,
    'Frozen Blackberries': 50,
    'Frozen Blueberries': 50,
    'Frozen Broccoli Florets': 50,
    'Frozen Broccoli': 50,
    'Frozen Carrots': 50,
    'Frozen Cheese Ravioli': 50,
    'Frozen Cherries': 50,
    'Frozen Chopped Broccoli': 50,
    'Frozen Chopped Spinach': 50,
    'Frozen Corn Kernels': 50,
    'Frozen Corn': 50,
    'Frozen Edamame Beans': 50,
    'Frozen Green Beans': 50,
    'Frozen Hash Browns': 50,
    'Frozen Lemonade Concentrate': 50,
    'Frozen Lima Beans': 50,
    'Frozen Limeade Concentrate': 50,
    'Frozen Limeade': 50,
    'Frozen Mango': 50,
    'Frozen Meatballs': 50,
    'Frozen Okra': 50,
    'Frozen Onion Rings': 50,
    'Frozen Peach Slices': 50,
    'Frozen Peaches': 50,
    'Frozen Peas': 50,
    'Frozen Pie Crust': 50,
    'Frozen Pound Cake': 50,
    'Frozen Raspberries': 50,
    'Frozen Ravioli': 50,
    'Frozen Shelled Edamame': 50,
    'Frozen Spinach': 50,
    'Frozen Strawberries': 50,
    'Frozen Sweet Corn': 50,
    'Frozen Sweet Peas': 50,
    'Frozen Tater Tots': 50,
    'Frozen Vegetables': 50,
    'Frozen Whipped Topping': 50,
    'Fruit Cocktail': 50,
    'Fruit Juice Concentrate': 35,
    'Fruit Juice': 50,
    'Fruit Liqueur': 20,
    'Fruit Preserve': 20,
    'Fruit Syrup': 20,
    'Fryer Chickens': 50,
    'Fudge Sauce': 35,
    'Fully Cooked Ham': 50,
    'Gaeta Olives': 50,
    'Gala Apples': 50,
    'Garam Masala': 50,
    'Garbanzo Beans': 50,
    'Garden Peas': 50,
    'Garlic Bread': 50,
    'Garlic Bulb': 50,
    'Garlic Chives': 50,
    'Garlic Cloves': 50,
    'Garlic Flakes': 50,
    'Garlic Juice': 50,
    'Garlic Oil': 35,
    'Garlic Paste': 35,
    'Garlic Pepper Seasoning': 50,
    'Garlic Powder': 35,
    'Garlic Salt': 50,
    'Garlic Sauce': 20,
    'Gelatin Sheet': 50,
    'Gelatin': 35,
    'Genoa Salami': 50,
    'Ghee': 35,
    'Ginger Ale': 50,
    'Ginger Beer': 50,
    'Ginger Extract': 20,
    'Ginger Juice': 50,
    'Ginger Liqueur': 35,
    'Ginger Powder': 20,
    'Ginger Root': 50,
    'Ginger Sauce': 20,
    'Ginger Syrup': 20,
    'Gingersnap Cookies': 50,
    'Glace Cherries': 50,
    'Glace De Viande': 50,
    'Globe Eggplant': 50,
    'Gluten-Free Oat': 50,
    'Gluten-Free Rolled Oats': 50,
    'Gluten-Free Tamari': 50,
    'Glutinous Rice': 50,
    'Goat Cheese Crumbles': 20,
    'Goat Cheese Logs': 20,
    'Goat Cheese Spread': 20,
    'Goat Cheese': 50,
    'Goat Milk Yogurt': 20,
    'Goat Milk': 20,
    'Goji Berries': 50,
    'Goji Berry Powder': 20,
    'Goji Berry Sauce': 20,
    'Goji Berry Syrup': 20,
    'Goji Berry Wine Vinegar': 20,
    'Goji Berry Wine': 20,
    'Goji Berry': 35,
    'Gold Potatoes': 50,
    'Golden Beets': 50,
    'Golden Brown Sugar': 50,
    'Golden Delicious Apples': 50,
    'Golden Mushroom Soup': 50,
    'Golden Raisins': 50,
    'Gorgonzola Cheese': 35,
    'Gorgonzola Dolce': 50,
    'Graham Cracker Crusts': 50,
    'Graham Crackers': 50,
    'Grain Alcohol': 50,
    'Grana Padano': 50,
    'Granulated Garlic': 50,
    'Grape Juice': 50,
    'Grape Leaves': 50,
    'Grape Tomatoes': 50,
    'Grapefruit Juice Concentrate': 35,
    'Grapefruit Juice': 50,
    'Grapefruit Segments': 50,
    'Green Apple': 50,
    'Green Beans': 50,
    'Green Bell Pepper': 50,
    'Green Cabbage': 50,
    'Green Cardamom Pods': 50,
    'Green Cherries': 50,
    'Green Chiles': 50,
    'Green Chili Flakes': 20,
    'Green Chili Powder': 20,
    'Green Chili Sauce': 20,
    'Green Chili Spice Mix': 20,
    'Green Chili': 20,
    'Green Coffee Beans': 50,
    'Green Curry': 50,
    'Green Grapes': 50,
    'Green Lentils': 50,
    'Green Lettuce': 50,
    'Green Olives': 50,
    'Green Onion': 50,
    'Green Onions': 50,
    'Green Peppercorns': 50,
    'Green Plantains': 50,
    'Green Tea Extract': 20,
    'Green Tea Leaves': 50,
    'Green Tea Liqueur': 20,
    'Green Tea Powder': 20,
    'Green Tea Spice Mix': 20,
    'Green Tea': 50,
    'Green Tomatoes': 50,
    'Grill Seasoning': 50,
    'Grilling Cheese': 50,
    'Grilling Sausage': 50,
    'Ground Allspice': 35,
    'Ground Almonds': 50,
    'Ground Anise Seed': 50,
    'Ground Beef And Pork': 35,
    'Ground Beef': 50,
    'Ground Black Pepper': 50,
    'Ground Black Peppercorn': 20,
    'Ground Cardamom': 50,
    'Ground Celery Seed': 50,
    'Ground Chicken': 50,
    'Ground Cinnamon': 50,
    'Ground Clove': 35,
    'Ground Cloves': 50,
    'Ground Coriander': 50,
    'Ground Cumin': 50,
    'Ground Dill': 20,
    'Ground Duck': 50,
    'Ground Fenugreek': 50,
    'Ground Flaxseed': 35,
    'Ground Ginger': 50,
    'Ground Lamb': 50,
    'Ground Mace': 50,
    'Ground Marjoram': 20,
    'Ground Meat': 50,
    'Ground Mustard Seed': 35,
    'Ground Mustard': 35,
    'Ground Nutmeg': 50,
    'Ground Oregano': 20,
    'Ground Paprika': 20,
    'Ground Parsley': 20,
    'Ground Peppermint': 20,
    'Ground Pink Peppercorn': 20,
    'Ground Pork And Beef': 35,
    'Ground Pork Sausage': 35,
    'Ground Pork': 50,
    'Ground Poultry': 50,
    'Ground Red Pepper': 20,
    'Ground Rosemary': 20,
    'Ground Saffron': 20,
    'Ground Sage': 35,
    'Ground Sausage': 50,
    'Ground Seaweed': 20,
    'Ground Sesame Seed': 20,
    'Ground Shallot': 20,
    'Ground Shiitake Mushroom': 20,
    'Ground Shrimp': 20,
    'Ground Smoked Paprika': 20,
    'Ground Soy Sauce': 20,
    'Ground Star Anise Seed': 35,
    'Ground Star Anise': 50,
    'Ground Tamarind': 20,
    'Ground Tarragon': 20,
    'Ground Thyme': 35,
    'Ground Tomato': 20,
    'Ground Turkey': 50,
    'Ground Turmeric': 20,
    'Ground White Wine': 20,
    'Ground Whole Grain': 20,
    'Ground Whole Wheat Flour': 20,
    'Ground Whole Wheat Pasta': 20,
    'Ground Whole Wheat': 20,
    'Ground Wild Rice': 20,
    'Ground Wine': 20,
    'Ground Worcestershire Sauce': 20,
    'Ground Yeast': 20,
    'Ground Yellow Onion': 20,
    'Ground Yellow Pepper': 20,
    'Ground Yellow Rice': 20,
    'Ground Yellow Split Peas': 20,
    'Ground Zucchini': 20,
    'Gruyere Cheese': 50,
    'Guava Liqueur': 20,
    'Guava Nectar': 50,
    'Guava Paste': 50,
    'Guava Syrup': 20,
    'Halibut Fillets': 50,
    'Halibut Steaks': 50,
    'Hamburger Buns': 50,
    'Hamburger Rolls': 50,
    'Hard Cider': 50,
    'Hard Tofu': 50,
    'Haricot Beans': 50,
    'Hass Avocado': 50,
    'Hazelnut Extract': 20,
    'Hazelnut Liqueur': 20,
    'Hazelnut Oil': 35,
    'Hazelnut Powder': 20,
    'Hazelnut Sauce': 20,
    'Hazelnut Syrup': 20,
    'Hearts Of Palm': 50,
    'Heavy Cream': 50,
    'Heavy Whipping Cream': 50,
    'Heirloom Tomatoes': 50,
    'Herbal Tea': 50,
    'Herbs De Provence': 50,
    'Herbs Mix': 50,
    'Herbs-And-Spice Rub': 50,
    'Hickory Smoked Bacon': 50,
    'High Gluten Flour': 50,
    'Hoisin Sauce': 35,
    'Hominy Grits': 50,
    'Hominy': 50,
    'Honey Extract': 20,
    'Honey Liqueur': 20,
    'Honey Powder': 20,
    'Honey Sauce': 20,
    'Honey Syrup': 20,
    'Honeydew Melon': 50,
    'Horseradish Extract': 20,
    'Horseradish Powder': 20,
    'Horseradish Sauce': 20,
    'Horseradish Spice Mix': 20,
    'Horseradish Spice': 20,
    'Hot Chicken Stock': 50,
    'Hot Chili Flakes': 20,
    'Hot Chili Paste': 35,
    'Hot Chili Pepper': 35,
    'Hot Chili Powder': 20,
    'Hot Chili Sauce': 35,
    'Hot Chili Spice Mix': 20,
    'Hot Chili': 35,
    'Hot Cocoa Mix': 50,
    'Hot Dog Buns': 35,
    'Hot Dog Rolls': 35,
    'Hot Dogs': 50,
    'Hot Sauce': 50,
    'Hot Water': 50,
    'Huckleberries': 50,
    'Hush Puppies': 50,
    'Ice Cream Cones': 50,
    'Ice Cream Extract': 20,
    'Ice Cream Liqueur': 20,
    'Ice Cream Powder': 20,
    'Ice Cream Sandwiches': 50,
    'Ice Cream Sauce': 20,
    'Ice Cream Syrup': 20,
    'Ice Cream Topping': 35,
    'Ice Cream': 50,
    'Iceberg Lettuce': 50,
    'Instant Chocolate Pudding': 35,
    'Instant Coffee Extract': 20,
    'Instant Coffee Granules': 50,
    'Instant Coffee Liqueur': 20,
    'Instant Coffee Powder': 20,
    'Instant Coffee Sauce': 20,
    'Instant Coffee Syrup': 20,
    'Instant Coffee': 50,
    'Instant Espresso Powder': 50,
    'Instant Hot Chocolate Mix': 50,
    'Instant Oatmeal': 50,
    'Instant Pudding': 20,
    'Instant Rice': 50,
    'Instant Tea': 50,
    'Instant Vanilla Pudding': 50,
    'Irish Cream Liqueur': 35,
    'Irish Liqueur': 20,
    'Irish Whiskey': 50,
    'Italian Bread': 50,
    'Italian Cheese Blend': 50,
    'Italian Herb Extract': 20,
    'Italian Herb Powder': 20,
    'Italian Herb Spice Mix': 20,
    'Italian Herbs': 50,
    'Italian Plum Tomatoes': 50,
    'Italian Sausage': 50,
    'Jalapeno Extract': 20,
    'Jalapeno Paste': 35,
    'Jalapeno Pepper': 35,
    'Jalapeno Peppers': 50,
    'Jalapeno Powder': 20,
    'Jalapeno Relish': 50,
    'Jalapeno Sauce Extract': 20,
    'Jalapeno Sauce Powder': 20,
    'Jalapeno Sauce Sauce': 20,
    'Jalapeno Sauce': 35,
    'Jalapeno Spice Mix': 20,
    'Jalapeno Spice': 20,
    'Jam': 35,
    'Jam Extract': 20,
    'Jam Liqueur': 20,
    'Jam Powder': 20,
    'Jam Sauce': 20,
    'Jam Syrup': 20,
    'Jambalaya Rice': 50,
    'Jasmine Green Tea': 35,
    'Jasmine Rice': 50,
    'Jasmine Tea': 20,
    'Jasmine Tea Liqueur': 20,
    'Jasmine Tea Powder': 20,
    'Jelly': 35,
    'Jelly Extract': 20,
    'Jelly Liqueur': 20,
    'Jelly Powder': 20,
    'Jelly Sauce': 20,
    'Jelly Syrup': 20,
    'Jerk Seasoning': 50,
    'Jicama Sticks': 50,
    'Jicama': 50,
    'Jumbo Shrimp': 50,
    'Juniper Berry Extract': 20,
    'Juniper Berry Powder': 20,
    'Juniper Berry': 20,
    'Kaffir Lime Leaf': 20,
    'Kaffir Lime Leaves': 35,
    'Kalamata Olives': 50,
    'Kale Leaves': 50,
    'Kangaroo Meat': 50,
    'Ketchup Sauce': 35,
    'Ketchup': 50,
    'Kielbasa Sausage': 50,
    'Kimchi': 35,
    'King Crab Legs': 50,
    'King Prawns': 50,
    'Kirschwasser': 50,
    'Kohlrabi': 50,
    'Kombu': 35,
    'Kombu Extract': 20,
    'Kombu Powder': 20,
    'Kosher Salt': 50,
    'Kumquats': 50,
    'Labneh': 50,
    'Lager Beer': 50,
    'Lamb Bones': 50,
    'Lamb Chops': 50,
    'Lamb Fillet': 50,
    'Lamb Kidney': 50,
    'Lamb Liver': 50,
    'Lamb Loin Chops': 50,
    'Lamb Loin Roast': 50,
    'Lamb Meat': 50,
    'Lamb Neck': 50,
    'Lamb Rack': 50,
    'Lamb Ribs': 50,
    'Lamb Rump': 50,
    'Lamb Shank': 50,
    'Lamb Shoulder Chops': 50,
    'Lamb Shoulder': 50,
    'Lamb Steaks': 50,
    'Lamb Stock': 50,
    'Lamb Tenderloin': 50,
    'Lard': 50,
    'Large Eggs': 50,
    'Lasagna Noodles': 50,
    'Lavender Extract': 20,
    'Lavender Flower': 20,
    'Lavender Flower Extract': 20,
    'Lavender Flower Powder': 20,
    'Lavender Powder': 20,
    'Lavender Spice Mix': 20,
    'Lavender': 5,
    'Leaf Lettuce': 50,
    'Leeks': 50,
    'Lemon Balm': 50,
    'Lemon Balm Extract': 20,
    'Lemon Balm Powder': 20,
    'Lemon Extract': 35,
    'Lemon Leaves': 50,
    'Lemon Peel': 20,
    'Lemon Peel Extract': 20,
    'Lemon Peel Powder': 20,
    'Lemon Pepper': 50,
    'Lemon Slice': 50,
    'Lemon Sorbet': 50,
    'Lemon Verbena': 50,
    'Lemon-Lime Soda': 50,
    'Lemonade': 50,
    'Lemongrass': 35,
    'Lemongrass Extract': 20,
    'Lemongrass Powder': 20,
    'Lentils': 50,
    'Lettuce Leaves': 50,
    'Lettuce': 50,
    'Light Brown Sugar': 50,
    'Light Corn Syrup': 35,
    'Light Muscovado Sugar': 50,
    'Light Rum': 35,
    'Light Soy': 50,
    'Light Turkey Meat': 50,
    'Lima Beans': 50,
    'Lime Extract': 35,
    'Lime Leaf': 20,
    'Lime Leaves': 50,
    'Lime Peel': 20,
    'Lime Powder': 20,
    'Lime Preserve': 35,
    'Lime Slice': 50,
    'Lime Spice Mix': 20,
    'Lime Syrup': 35,
    'Lime': 20,
    'Liquid Smoke': 50,
    'Liquid Smoke Extract': 20,
    'Liquid Smoke Powder': 20,
    'Little Neck Clams': 50,
    'Lo Mein Noodles': 50,
    'Lobster Claws': 50,
    'Lobster Meat': 50,
    'Lobster Tail': 50,
    'Long Grain Rice': 50,
    'Long Grain White Rice': 50,
    'Long Pepper': 20,
    'Long Pepper Extract': 20,
    'Long Pepper Powder': 20,
    'Loose Tea': 50,
    'Loquat': 50,
    'Lotus Root': 50,
    'Lotus Root Extract': 20,
    'Lotus Root Powder': 20,
    'Lotus Seed': 35,
    'Low Fat Milk': 50,
    'Low Fat Yogurt': 50,
    'Low-Fat Cottage Cheese': 50,
    'Low-Fat Croutons': 50,
    'Low-Fat Mayonnaise': 50,
    'Low-Fat Refried Beans': 50,
    'Low-Fat Sour Cream': 50,
    'Low-Fat Yogurt': 50,
    'Lychee': 50,
    'Mace Extract': 20,
    'Mace Powder': 20,
    'Mackerel Fillets': 50,
    'Mackerel Steaks': 50,
    'Madder Root': 20,
    'Madder Root Extract': 20,
    'Madder Root Powder': 20,
    'Madras Curry Powder': 35,
    'Madras Curry Powder Extract': 20,
    'Madras Curry Powder Powder': 20,
    'Malt Vinegar': 50,
    'Manchego Cheese': 50,
    'Mango Powder Extract': 20,
    'Mango Powder Powder': 20,
    'Mango Powder': 20,
    'Manioc': 50,
    'Maple Sugar': 50,
    'Maple Syrup': 50,
    'Maraschino Cherries': 50,
    'Margarine': 50,
    'Marigold Flower': 20,
    'Marigold Flower Extract': 20,
    'Marigold Flower Powder': 20,
    'Marigold Flower Spice Mix': 20,
    'Marinara Sauce': 50,
    'Marinated Artichoke Hearts': 50,
    'Marinated Tofu': 50,
    'Marjoram': 35,
    'Marjoram Extract': 20,
    'Marjoram Powder': 20,
    'Marjoram Spice Mix': 20,
    'Marmalade': 50,
    'Marsala Wine': 50,
    'Masa Harina': 50,
    'Mascarpone Cheese': 50,
    'Matzo Meal': 50,
    'Mayonnaise': 50,
    'Meat Marinade': 50,
    'Meat Tenderizer': 50,
    'Meatballs': 50,
    'Melon': 50,
    'Meringue': 50,
    'Mesclun Greens': 50,
    'Mexican Oregano': 50,
    'Millet': 50,
    'Mint Extract': 20,
    'Mint Leaves': 50,
    'Mint Powder': 20,
    'Mint Spice Mix': 20,
    'Mint': 5,
    'Mirin': 50,
    'Miso Paste': 35,
    'Mixed Dried Fruit': 50,
    'Mixed Greens': 50,
    'Mixed Herbs': 50,
    'Mixed Mushrooms': 50,
    'Mixed Nuts': 50,
    'Mixed Vegetables': 50,
    'Mocha Coffee': 50,
    'Molasses': 35,
    'Mole Paste': 35,
    'Monkfish Fillets': 50,
    'Monkfish Tails': 50,
    'Morel Mushroom': 20,
    'Morel Mushroom Extract': 20,
    'Morel Mushroom Powder': 20,
    'Morel Mushroom Spice Mix': 20,
    'Mousse': 50,
    'Mozzarella Balls': 50,
    'Mozzarella Cheese': 50,
    'Msg': 35,
    'Muffin Mix': 50,
    'Muffins': 50,
    'Mugwort': 50,
    'Mung Bean Sprouts': 50,
    'Mung Beans': 50,
    'Mushroom Broth': 50,
    'Mushroom Extract': 20,
    'Mushroom Gravy': 50,
    'Mushroom Powder': 20,
    'Mushroom Spice Mix': 20,
    'Mushroom': 5,
    'Mussel Meat': 50,
    'Mussels': 50,
    'Mustard Extract': 20,
    'Mustard Greens': 50,
    'Mustard Oil': 35,
    'Mustard Paste': 35,
    'Mustard Powder': 20,
    'Mustard Seeds': 50,
    'Mustard Spice Mix': 20,
    'Mustard': 5,
    'Navy Beans': 50,
    'Nectarine': 50,
    'New York Strip Steak': 50,
    'Nigella Seeds': 50,
    'Nori Sheets': 50,
    'Nori': 50,
    'Nutmeg Extract': 20,
    'Nutmeg Powder': 20,
    'Nutmeg Spice Mix': 20,
    'Nutmeg': 5,
    'Nutritional Yeast': 50,
    'Oat Bran': 50,
    'Oat Flour': 35,
    'Oat Milk': 50,
    'Oat Syrup': 35,
    'Oatmeal': 50,
    'Okra': 50,
    'Old Bay Seasoning': 50,
    'Old Fashioned Oats': 50,
    'Olive Oil Spray': 35,
    'Olive Oil': 50,
    'Onion Extract': 20,
    'Onion Powder': 50,
    'Onion Salt': 50,
    'Onion Spice Mix': 20,
    'Onion': 5,
    'Orange Extract': 20,
    'Orange Flower Extract': 20,
    'Orange Flower Powder': 20,
    'Orange Flower Spice Mix': 20,
    'Orange Flower Water': 50,
    'Orange Flower': 20,
    'Orange Marmalade': 50,
    'Orange Peel': 50,
    'Orange Peel Extract': 20,
    'Orange Peel Powder': 20,
    'Orange Peel Spice Mix': 20,
    'Orange Powder': 20,
    'Orange Roughy Fillets': 50,
    'Orange Slice': 50,
    'Orange Spice Mix': 20,
    'Orange': 5,
    'Oregano Extract': 20,
    'Oregano Powder': 20,
    'Oregano Spice Mix': 20,
    'Oregano': 5,
    'Oyster Mushrooms': 50,
    'Oyster Sauce': 50,
    'Oyster Sauce Extract': 20,
    'Oyster Sauce Powder': 20,
    'Oyster Sauce Spice Mix': 20,
    'Oysters': 50,
    'Palm Sugar': 50,
    'Palm Sugar Extract': 20,
    'Palm Sugar Powder': 20,
    'Palm Sugar Spice Mix': 20,
    'Palmini Pasta': 50,
    'Panko Breadcrumbs': 50,
    'Pappardelle Pasta': 50,
    'Paprika': 50,
    'Paprika Extract': 20,
    'Paprika Powder': 35,
    'Paprika Spice Mix': 20,
    'Parboiled Rice': 50,
    'Parma Ham': 50,
    'Parmesan Cheese': 50,
    'Parmesan Rind': 50,
    'Parmigiano-Reggiano Cheese': 50,
    'Parsley Extract': 20,
    'Parsley Leaves': 50,
    'Parsley Powder': 20,
    'Parsley Root': 50,
    'Parsley Spice Mix': 20,
    'Parsley Sprigs': 50,
    'Parsley': 50,
    'Parsnip': 50,
    'Part-Skim Mozzarella': 50,
    'Part-Skim Ricotta': 50,
    'Pasilla Chile': 50,
    'Pasilla Chile Extract': 20,
    'Pasilla Chile Powder': 20,
    'Pasilla Chile Spice Mix': 20,
    'Passion Fruit Juice': 50,
    'Passion Fruit Nectar': 50,
    'Passion Fruit Pulp': 50,
    'Pasta Sauce': 50,
    'Pasta Shells': 50,
    'Pasta': 50,
    'Pastry Cream': 50,
    'Pastry Dough': 50,
    'Pastry Flour': 50,
    'Peach Halves': 50,
    'Peach Nectar': 50,
    'Peaches': 50,
    'Peanut Butter': 50,
    'Peanut Oil': 50,
    'Peanut Sauce': 50,
    'Peanut': 35,
    'Peanuts': 50,
    'Pearl Barley': 50,
    'Pearl Onions': 50,
    'Pecans': 50,
    'Penne Pasta': 50,
    'Peppercorns': 50,
    'Peppermint Candy': 50,
    'Peppermint Extract': 50,
    'Peppermint Oil': 50,
    'Peppermint Powder': 20,
    'Peppermint Schnapps': 50,
    'Peppermint Spice Mix': 20,
    'Peppermint': 5,
    'Pepperoncini': 50,
    'Pesto Paste': 35,
    'Pesto Sauce': 50,
    'Pesto': 50,
    'Pheasant': 50,
    'Pickle Juice': 50,
    'Pickled Beets': 50,
    'Pickled Cucumber': 50,
    'Pickled Ginger': 50,
    'Pickled Jalapenos': 50,
    'Pickled Onions': 50,
    'Pickled Radishes': 50,
    'Pickled Red Onions': 50,
    'Pickles': 50,
    'Pie Crust': 50,
    'Pie Filling': 50,
    'Pie Shells': 50,
    'Pignoli Nuts': 50,
    'Pimento Cheese': 50,
    'Pimentos': 50,
    'Pine Nut Oil': 35,
    'Pine Nut': 50,
    'Pine Nuts': 50,
    'Pineapple Chunks': 50,
    'Pineapple Juice': 50,
    'Pineapple Preserve': 35,
    'Pineapple Slices': 50,
    'Pineapple': 50,
    'Pink Beans': 50,
    'Pink Himalayan Salt': 50,
    'Pink Peppercorn': 50,
    'Pink Peppercorn Extract': 20,
    'Pink Peppercorn Powder': 20,
    'Pink Peppercorn Spice Mix': 20,
    'Pinto Beans': 50,
    'Pistachio Nuts': 50,
    'Pistachio Oil': 35,
    'Pita Bread': 50,
    'Pizza Sauce': 35,
    'Plain Flour': 50,
    'Plain Greek Yogurt': 50,
    'Plain Yogurt': 50,
    'Plant-Based Milk': 50,
    'Plantain Chips': 50,
    'Plantain': 50,
    'Plum Tomatoes': 50,
    'Plums': 50,
    'Poaching Liquid': 50,
    'Poblano Pepper': 50,
    'Polenta Cornmeal': 50,
    'Polenta': 50,
    'Pomegranate Molasses': 35,
    'Pomegranate Preserve': 35,
    'Pomegranate Syrup': 35,
    'Popcorn Kernels': 50,
    'Popcorn': 50,
    'Popsicle Sticks': 50,
    'Porcini Mushroom': 50,
    'Porcini Mushroom Extract': 20,
    'Porcini Mushroom Powder': 20,
    'Porcini Mushroom Spice Mix': 20,
    'Pork And Beans': 50,
    'Pork Bacon': 50,
    'Pork Bones': 50,
    'Pork Bouillon': 50,
    'Pork Butt': 50,
    'Pork Chops': 50,
    'Pork Fat': 50,
    'Pork Fillet': 50,
    'Pork Gravy': 50,
    'Pork Hocks': 50,
    'Pork Loin Roast': 50,
    'Pork Loin': 50,
    'Pork Ribs': 50,
    'Pork Rinds': 50,
    'Pork Sausage': 50,
    'Pork Shoulder Roast': 50,
    'Pork Shoulder': 50,
    'Pork Spare Ribs': 50,
    'Pork Steaks': 50,
    'Pork Stock': 50,
    'Pork Tenderloin': 50,
    'Port Wine': 50,
    'Portobello Mushroom Caps': 50,
    'Portobello Mushrooms': 50,
    'Potato Chips': 50,
    'Potato Flakes': 50,
    'Potato Flour': 35,
    'Potato Gnocchi': 50,
    'Potato Starch': 35,
    'Potato Waffles': 50,
    'Potatoes Salad': 50,
    'Potatoes Wedges': 50,
    'Potatoes': 50,
    'Potpie Crust': 50,
    'Potpie Dough': 50,
    'Potting Soil': 50,
    'Poultry Seasoning': 20,
    'Poultry Seasoning Extract': 20,
    'Poultry Seasoning Powder': 20,
    'Poultry Seasoning Spice Mix': 20,
    'Pound Cake': 50,
    'Pout Fillets': 50,
    'Praline': 50,
    'Pre-Cooked Shrimp': 50,
    'Pre-Made Pie Crust': 50,
    'Prepared Horseradish': 50,
    'Preserve': 35,
    'Pretzel Dough': 50,
    'Pretzels': 50,
    'Primavera Vegetables': 50,
    'Processed Cheese': 50,
    'Prosciutto': 50,
    'Provolone Cheese': 50,
    'Prune Juice': 50,
    'Prunes': 50,
    'Pudding Mix': 35,
    'Puff Pastry Dough': 50,
    'Puff Pastry Shells': 50,
    'Puff Pastry': 50,
    'Pumpkin Pie Filling': 50,
    'Pumpkin Pie Spice': 35,
    'Pumpkin Seed': 35,
    'Pumpkin Spice': 35,
    'Pumpkin': 50,
    'Pure Cane Sugar': 50,
    'Quark Cheese': 50,
    'Quick Cooking Oats': 50,
    'Quick-Cooking Rice': 50,
    'Quince Paste': 50,
    'Quince': 50,
    'Quinoa Extract': 20,
    'Quinoa Powder': 20,
    'Quinoa Spice Mix': 20,
    'Quinoa': 5,
    'Rabbit Meat': 50,
    'Radiatore Pasta': 50,
    'Radish Seed': 35,
    'Radish Sprouts': 50,
    'Radishes': 50,
    'Raisin Bran Cereal': 50,
    'Raisins': 50,
    'Ramen Noodles': 50,
    'Raspberry Filling': 50,
    'Raspberry Jam': 50,
    'Raspberry Jelly': 50,
    'Raspberry Liqueur': 50,
    'Raspberry Preserve': 35,
    'Raspberry Preserves': 50,
    'Raw Chicken': 50,
    'Raw Honey': 50,
    'Raw Peanuts': 50,
    'Raw Shrimp': 50,
    'Red Bean': 20,
    'Red Bean Extract': 20,
    'Red Bean Powder': 20,
    'Red Bean Spice Mix': 20,
    'Red Chili': 35,
    'Red Chili Flakes': 35,
    'Red Chili Powder': 35,
    'Red Chili Sauce': 35,
    'Red Chili Spice Mix': 20,
    'Red Curry Paste': 35,
    'Red Food Coloring': 35,
    'Red Pepper': 20,
    'Red Pepper Extract': 20,
    'Red Pepper Powder': 20,
    'Red Pepper Spice Mix': 20,
    'Red Wine': 50,
    'Red Wine Extract': 20,
    'Red Wine Powder': 20,
    'Red Wine Spice Mix': 20,
    'Red Wine Vinegar': 35,
    'Refined Sugar': 50,
    'Refried Beans': 50,
    'Relish': 50,
    'Remoulade Sauce': 50,
    'Rhubarb': 50,
    'Rib Eye Steak': 50,
    'Rib Roast': 50,
    'Rice Extract': 20,
    'Rice Flour': 35,
    'Rice Noodle': 20,
    'Rice Noodle Extract': 20,
    'Rice Noodle Powder': 20,
    'Rice Noodle Spice Mix': 20,
    'Rice Powder': 20,
    'Rice Spice Mix': 20,
    'Rice Syrup': 35,
    'Rice': 5,
    'Ricotta Cheese': 50,
    'Ricotta Salata': 50,
    'Rigatoni Pasta': 50,
    'Risotto Rice': 50,
    'Roast Beef': 50,
    'Roast Duck': 50,
    'Roast Pork': 50,
    'Roast Turkey': 50,
    'Roasted Beef': 50,
    'Roasted Beets': 50,
    'Roasted Bell Pepper': 50,
    'Roasted Chicken': 50,
    'Roasted Garlic Cloves': 50,
    'Roasted Garlic': 50,
    'Roasted Pecans': 50,
    'Roasted Peppers': 50,
    'Roasted Pork': 50,
    'Roasted Red Pepper': 50,
    'Roasted Red Peppers': 50,
    'Roasted Sweet Potato': 50,
    'Roasted Turkey': 50,
    'Roasted Vegetables': 50,
    'Roasted Walnuts': 50,
    'Rock Salt': 50,
    'Rolled Oat': 35,
    'Rolled Oats': 50,
    'Romaine Lettuce': 50,
    'Romanesco Broccoli': 50,
    'Roquefort Cheese': 50,
    'Rose Hips': 50,
    'Rose Water': 50,
    'Rosemary Extract': 35,
    'Rosemary Oil': 35,
    'Rosemary Powder': 20,
    'Rosemary Spice Mix': 20,
    'Rosemary Sprigs': 50,
    'Rosemary': 5,
    'Rotini Pasta': 50,
    'Round Steak': 50,
    'Rye Bread': 50,
    'Rye Flour': 50,
    'Rye Whiskey': 50,
    'Safflower Oil': 35,
    'Saffron Threads': 50,
    'Saffron Extract': 20,
    'Saffron Powder': 20,
    'Saffron Spice Mix': 20,
    'Saffron': 5,
    'Sage Leaves': 50,
    'Sage Extract': 20,
    'Sage Powder': 20,
    'Sage Spice Mix': 20,
    'Sage': 5,
    'Sake': 50,
    'Salad Dressing': 50,
    'Salad Greens': 50,
    'Salad Mix': 50,
    'Salami': 50,
    'Salmon Fillet': 50,
    'Salmon Roe': 50,
    'Salmon Steaks': 50,
    'Salsa Verde Sauce': 35,
    'Salsa Verde': 50,
    'Salsa': 50,
    'Salt Pork': 50,
    'Saltine Crackers': 50,
    'Sambuca': 50,
    'Sandwich Rolls': 50,
    'Sardines': 50,
    'Sashimi Grade Tuna': 50,
    'Saucisson Sec': 50,
    'Sausage Casings': 50,
    'Sausage Meat': 50,
    'Sausage Patties': 50,
    'Sausage': 35,
    'Savoy Cabbage': 50,
    'Scallops': 50,
    'Schnapps': 50,
    'Scotch Bonnet Pepper': 50,
    'Scotch Broth': 50,
    'Scotch Whiskey': 50,
    'Sea Bass Fillets': 50,
    'Sea Bass': 50,
    'Sea Salt': 50,
    'Seaweed Extract': 20,
    'Seaweed Powder': 20,
    'Seaweed Spice Mix': 20,
    'Seaweed': 35,
    'Seaweed Spice': 20,
    'Semolina Flour': 50,
    'Semolina': 50,
    'Serrano Ham': 50,
    'Serrano Pepper': 50,
    'Sesame Oil': 35,
    'Sesame Paste': 35,
    'Sesame Seed': 35,
    'Sesame Seed Extract': 20,
    'Sesame Seed Powder': 20,
    'Sesame Seed Spice Mix': 20,
    'Sesame Seeds': 50,
    'Seven Grain Bread': 50,
    'Shallot': 35,
    'Shallot Extract': 20,
    'Shallot Powder': 20,
    'Shallot Spice Mix': 20,
    'Shaved Chocolate': 50,
    'Shaved Parmesan': 50,
    'Shea Butter': 35,
    'Sheep Cheese': 50,
    'Shell Pasta': 50,
    'Shellfish': 50,
    'Sherbet': 50,
    'Sherry Vinegar': 50,
    'Shiitake Mushroom': 50,
    'Shiitake Mushroom Extract': 20,
    'Shiitake Mushroom Powder': 20,
    'Shiitake Mushroom Spice Mix': 20,
    'Shirataki Noodles': 50,
    'Shredded Cheese': 50,
    'Shredded Coconut': 50,
    'Shredded Lettuce': 50,
    'Shredded Mozzarella': 50,
    'Shredded Parmesan': 50,
    'Shredded Pork': 50,
    'Shredded Wheat Cereal': 50,
    'Shredded White Cheddar': 50,
    'Shredded White Cheese': 50,
    'Shrimp': 50,
    'Shrimp Extract': 20,
    'Shrimp Paste': 50,
    'Shrimp Powder': 20,
    'Shrimp Sauce': 35,
    'Shrimp Shells': 50,
    'Shrimp Spice Mix': 20,
    'Shrimp Stock': 50,
    'Side Pork': 50,
    'Silken Tofu': 50,
    'Sirloin Steak': 50,
    'Skim Milk Powder': 50,
    'Skim Milk': 50,
    'Skinless Chicken': 50,
    'Skinless Salmon Fillets': 50,
    'Skinless Turkey Breast': 50,
    'Skinned Halibut Fillets': 50,
    'Sloppy Joe Sauce': 50,
    'Small Eggs': 50,
    'Smoked Paprika': 35,
    'Smoked Paprika Extract': 20,
    'Smoked Paprika Powder': 20,
    'Smoked Paprika Spice Mix': 20,
    'Smoked Trout': 50,
    'Snapper Fillets': 50,
    'Soba Noodles': 50,
    'Soft Cheese': 50,
    'Soft Shell Crabs': 50,
    'Soft Tofu': 50,
    'Solomillo': 50,
    'Somen Noodles': 50,
    'Sour Cherries': 50,
    'Sour Cream': 50,
    'Sour Dough Bread': 50,
    'Sourdough Bread': 50,
    'Southern Comfort': 50,
    'Soy Beans': 50,
    'Soy Milk': 50,
    'Soy Nuts': 50,
    'Soy Sauce': 50,
    'Soy Sauce Extract': 20,
    'Soy Sauce Powder': 20,
    'Soy Sauce Spice Mix': 20,
    'Soybean Oil': 35,
    'Spaghetti Noodles': 50,
    'Spaghetti Pasta': 50,
    'Spaghetti Sauce': 35,
    'Spareribs': 50,
    'Sparkling Wine': 50,
    'Spearmint Leaves': 50,
    'Specialty Salt': 50,
    'Spelt Flour': 50,
    'Spice Blend': 35,
    'Spice Rub': 35,
    'Spiced Rum': 50,
    'Spinach Leaves': 50,
    'Spinach Tortillas': 50,
    'Spinach': 50,
    'Split Peas': 50,
    'Spring Greens': 50,
    'Spring Roll Wrappers': 50,
    'Spring Water': 50,
    'Squid Ink': 50,
    'Squid': 50,
    'St. Germain Liqueur': 50,
    'Star Anise': 50,
    'Star Anise Extract': 20,
    'Star Anise Powder': 20,
    'Star Anise Seed': 35,
    'Star Anise Spice Mix': 20,
    'Steak Rub': 35,
    'Steak Sauce': 50,
    'Steamed Rice': 50,
    'Steamed White Rice': 50,
    'Stella Artois': 50,
    'Stir-Fry Sauce': 50,
    'Stir-Fry Vegetables': 50,
    'Stout Beer': 50,
    'Strawberries': 50,
    'Strawberry Extract': 35,
    'Strawberry Gelatin': 50,
    'Strawberry Jam': 50,
    'Strawberry Jelly': 50,
    'Strawberry Preserve': 35,
    'Strawberry Preserves': 50,
    'Stuffing Mix': 50,
    'Sub Rolls': 50,
    'Sugar Cubes': 50,
    'Sugar Snap Peas': 50,
    'Sugar Substitute': 50,
    'Sugar Syrup': 35,
    'Sugar Wafers': 50,
    'Sun-Dried Tomatoes': 50,
    'Sunflower Oil': 35,
    'Sunflower Seed Butter': 50,
    'Sunflower Seed': 35,
    'Sunflower Seeds': 50,
    'Sweet Black Cherries': 50,
    'Sweet Corn': 50,
    'Sweet Pickle Relish': 50,
    'Sweet Potatoes': 50,
    'Sweet Red Wine': 35,
    'Sweet Rice': 50,
    'Sweet Soy Sauce': 35,
    'Sweet Tea': 50,
    'Sweet Wine': 35,
    'Swiss Cheese': 50,
    'Syrah Wine': 50,
    'Tabasco Sauce': 50,
    'Taco Seasoning': 35,
    'Taco Shells': 50,
    'Tagliatelle Pasta': 50,
    'Tahini Paste': 35,
    'Tahini': 50,
    'Tamari Soy': 50,
    'Tamari': 35,
    'Tamarind Paste': 50,
    'Tamarind Pulp': 50,
    'Tamarind Water': 50,
    'Tamarind': 5,
    'Tamarind Extract': 20,
    'Tamarind Powder': 20,
    'Tamarind Spice Mix': 20,
    'Tangelos': 50,
    'Tarragon Extract': 35,
    'Tarragon Leaves': 50,
    'Tarragon Powder': 20,
    'Tarragon Spice Mix': 20,
    'Tarragon': 5,
    'Tart Apples': 50,
    'Tart Cherries': 50,
    'Tart Shells': 50,
    'Tater Tots': 50,
    'Tea Bag': 50,
    'Tea Leaves': 50,
    'Tea Mix': 50,
    'Tea Powder': 35,
    'Tea Spice': 35,
    'Tenderloin Steaks': 50,
    'Tequila': 50,
    'Teriyaki Sauce Mix': 35,
    'Teriyaki Sauce': 50,
    'Texas Toast': 50,
    'Thick Cut Bacon': 50,
    'Thin Spaghetti': 50,
    'Thinly Sliced Chicken': 50,
    'Thinly Sliced Ham': 50,
    'Thinly Sliced Onion': 50,
    'Thinly Sliced Pork': 50,
    'Thinly Sliced Prosciutto': 50,
    'Thinly Sliced Shallots': 50,
    'Thinly Sliced Steak': 50,
    'Thyme Extract': 35,
    'Thyme Leaves': 35,
    'Thyme Powder': 20,
    'Thyme Seed': 35,
    'Thyme Spice Mix': 20,
    'Thyme': 5,
    'Tilsit Cheese': 50,
    'Toast': 50,
    'Tobasco Sauce': 50,
    'Tofu': 50,
    'Tomatillos': 50,
    'Tomato Concentrate': 50,
    'Tomato Extract': 20,
    'Tomato Jelly': 50,
    'Tomato Leaves': 50,
    'Tomato Paste': 50,
    'Tomato Powder': 20,
    'Tomato Puree': 50,
    'Tomato Salsa': 50,
    'Tomato Sauce': 50,
    'Tomato Spice Mix': 20,
    'Tomato': 5,
    'Tomatoes And Chiles': 50,
    'Tomatoes With Juice': 50,
    'Tomatoes': 50,
    'Top Round Steak': 50,
    'Top Round': 50,
    'Top Sirloin Steak': 50,
    'Top Sirloin': 50,
    'Tortilla Chips': 50,
    'Tortilla Wraps': 50,
    'Tortillas': 50,
    'Tostada Shells': 50,
    'Truffle Cheese': 50,
    'Truffle Oil': 50,
    'Truffle Paste': 35,
    'Truffle Salt': 35,
    'Truffle Shavings': 35,
    'Truffle': 35,
    'Truffles': 50,
    'Tuna Fish': 50,
    'Tuna Oil': 35,
    'Tuna': 50,
    'Turkey Bacon': 50,
    'Turkey Base': 50,
    'Turkey Bones': 50,
    'Turkey Bouillon': 50,
    'Turkey Breast Tenderloins': 50,
    'Turkey Breast': 50,
    'Turkey Broth': 50,
    'Turkey Gravy': 50,
    'Turkey Ham': 50,
    'Turkey Hot Dogs': 50,
    'Turkey Legs': 50,
    'Turkey Liver': 50,
    'Turkey Meat': 50,
    'Turkey Parts': 50,
    'Turkey Sausage': 50,
    'Turkey Stock': 50,
    'Turkey Tenderloin': 50,
    'Turkey Thighs': 50,
    'Turkey Wings': 50,
    'Turmeric': 50,
    'Turmeric Extract': 20,
    'Turmeric Powder': 35,
    'Turmeric Root': 50,
    'Turmeric Spice Mix': 20,
    'Turnip Greens': 50,
    'Turnips': 50,
    'Unbleached All-Purpose Flour': 50,
    'Uncured Bacon': 50,
    'Uncured Ham': 50,
    'Undiluted Evaporated Milk': 50,
    'Unsweetened Apple Juice': 50,
    'Unsweetened Cocoa Powder': 35,
    'Unsweetened Cocoa': 50,
    'Unsweetened Coconut Milk': 35,
    'Unsweetened Coconut': 50,
    'Unsweetened Cranberry Juice': 50,
    'Unsweetened Grape Juice': 50,
    'Unsweetened Iced Coffee': 50,
    'Unsweetened Iced Tea': 50,
    'Unsweetened Instant Coffee': 50,
    'Unsweetened Shredded Coconut': 35,
    'Unsweetened Tea': 50,
    'Unsweetened Vanilla Almond Milk': 50,
    'Unsweetened Yogurt': 50,
    'Vanilla Bean': 35,
    'Vanilla Beans': 50,
    'Vanilla Extract': 95,
    'Vanilla Ice Cream': 50,
    'Vanilla Instant Pudding': 50,
    'Vanilla Sugar': 50,
    'Veal Bones': 50,
    'Veal Chops': 50,
    'Veal Fillet': 50,
    'Veal Kidney': 50,
    'Veal Liver': 50,
    'Veal Ribs': 50,
    'Veal Roast': 50,
    'Veal Scallops': 50,
    'Veal Shank': 50,
    'Veal Stew Meat': 50,
    'Veal Stock': 50,
    'Veal Tenderloin': 50,
    'Veal Top Round': 50,
    'Vegetable Broth': 50,
    'Vegetable Cooking Spray': 50,
    'Vegetable Gravy': 50,
    'Vegetable Juice': 35,
    'Vegetable Mix': 50,
    'Vegetable Oil Spray': 35,
    'Vegetable Oil Substitute': 35,
    'Vegetable Oil': 50,
    'Vegetable Peels': 50,
    'Vegetable Protein': 50,
    'Vegetable Puree': 35,
    'Vegetable Shortening': 50,
    'Vegetable Soup': 50,
    'Vegetable Stock Concentrate': 35,
    'Vegetable Stock Cube': 50,
    'Vegetable Stock Powder': 50,
    'Vegetable Stock': 50,
    'Vegetable Strips': 50,
    'Vegetable Tempura': 50,
    'Vegetable Tortillas': 50,
    'Vegetable Water': 50,
    'Vegetable-Based Mayonnaise': 50,
    'Vegetables': 50,
    'Vegetarian Bacon': 50,
    'Vegetarian Sausage': 50,
    'Velveeta Cheese': 50,
    'Venison': 50,
    'Vidalia Onion': 50,
    'Viili Yogurt': 50,
    'Vinegar': 35,
    'Walnut Oil': 35,
    'Walnut Paste': 35,
    'Water Chestnut Flour': 35,
    'Watermelon Seed': 35,
    'White Balsamic Vinegar': 50,
    'White Beans': 50,
    'White Bread': 50,
    'White Cabbage': 50,
    'White Cheddar': 50,
    'White Chocolate Chips': 50,
    'White Chocolate': 50,
    'White Cooking Wine': 50,
    'White Corn Meal': 50,
    'White Corn': 50,
    'White Cornmeal': 35,
    'White Flour': 50,
    'White Grape Juice': 50,
    'White Grapes': 50,
    'White Hominy': 50,
    'White Kidney Beans': 50,
    'White Lager': 50,
    'White Miso': 50,
    'White Onion': 50,
    'White Pearl Onions': 50,
    'White Pepper': 95,
    'White Quinoa': 50,
    'White Radish': 50,
    'White Rice Flour': 35,
    'White Rice Vinegar': 35,
    'White Rice': 50,
    'White Rum': 35,
    'White Sandwich Bread': 50,
    'White Sesame Seed': 35,
    'White Sesame Seeds': 50,
    'White Sugar': 50,
    'White Tequila': 35,
    'White Truffle Oil': 35,
    'White Tuna': 50,
    'White Vermouth': 50,
    'White Vinegar': 50,
    'White Wine': 50,
    'White Wine Extract': 20,
    'White Wine Powder': 20,
    'White Wine Spice Mix': 20,
    'White Wine Vinegar': 50,
    'Whitefish Fillets': 50,
    'Whole Allspice': 50,
    'Whole Almonds': 50,
    'Whole Baby Okra': 50,
    'Whole Chicken': 50,
    'Whole Clove': 35,
    'Whole Cloves': 50,
    'Whole Cranberry Sauce': 50,
    'Whole Grain Baguette': 50,
    'Whole Grain Bread': 50,
    'Whole Grain Buns': 50,
    'Whole Grain Extract': 20,
    'Whole Grain Flour': 35,
    'Whole Grain Mustard': 50,
    'Whole Grain Pasta': 50,
    'Whole Grain Powder': 20,
    'Whole Grain Rice': 35,
    'Whole Grain Spice Mix': 20,
    'Whole Grain Wheat Flour': 35,
    'Whole Grain': 35,
    'Whole Milk': 95,
    'Whole Okra': 50,
    'Whole Peeled Tomatoes': 50,
    'Whole Peppercorn': 50,
    'Whole Snapper': 50,
    'Whole Turkey': 50,
    'Whole Wheat Baguette': 50,
    'Whole Wheat Bread': 50,
    'Whole Wheat Breadcrumbs': 50,
    'Whole Wheat Buns': 50,
    'Whole Wheat Couscous': 50,
    'Whole Wheat Extract': 20,
    'Whole Wheat Flour': 50,
    'Whole Wheat Flour Extract': 20,
    'Whole Wheat Flour Powder': 20,
    'Whole Wheat Flour Spice Mix': 20,
    'Whole Wheat Fusilli': 50,
    'Whole Wheat Pasta': 50,
    'Whole Wheat Pasta Extract': 20,
    'Whole Wheat Pasta Powder': 20,
    'Whole Wheat Pasta Spice Mix': 20,
    'Whole Wheat Penne': 50,
    'Whole Wheat Pita': 50,
    'Whole Wheat Powder': 20,
    'Whole Wheat Rotini': 50,
    'Whole Wheat Spaghetti': 50,
    'Whole Wheat Spice Mix': 20,
    'Whole Wheat Tortillas': 50,
    'Wide Egg Noodles': 50,
    'Wide Rice Noodles': 50,
    'Wild Mushrooms': 50,
    'Wild Rice': 50,
    'Wild Rice Extract': 20,
    'Wild Rice Powder': 20,
    'Wild Rice Spice Mix': 20,
    'Wild Salmon': 50,
    'Wildflower Honey': 50,
    'Wine Extract': 20,
    'Wine Powder': 20,
    'Wine Spice Mix': 20,
    'Wine Vinegar': 50,
    'Wing Sauce': 50,
    'Winter Savory': 50,
    'Winter Squash': 50,
    'Won Ton Wrappers': 50,
    'Wonton Skins': 50,
    'Wonton Wrappers': 50,
    'Worcestershire Sauce': 50,
    'Worcestershire Sauce Extract': 20,
    'Worcestershire Sauce Powder': 20,
    'Worcestershire Sauce Spice Mix': 20,
    'Xanthan Gum': 50,
    'Yeast Extract': 20,
    'Yeast Powder': 20,
    'Yeast Spice Mix': 20,
    'Yellow Bell Pepper': 50,
    'Yellow Cake Mix': 50,
    'Yellow Corn': 50,
    'Yellow Crookneck Squash': 50,
    'Yellow Curry Paste': 35,
    'Yellow Food Coloring': 50,
    'Yellow Heirloom Tomatoes': 50,
    'Yellow Hominy': 50,
    'Yellow Lentils': 50,
    'Yellow Miso': 35,
    'Yellow Mustard Seed': 35,
    'Yellow Mustard Seeds': 50,
    'Yellow Mustard': 50,
    'Yellow Onion': 50,
    'Yellow Onion Extract': 20,
    'Yellow Onion Powder': 20,
    'Yellow Onion Spice Mix': 20,
    'Yellow Pepper': 50,
    'Yellow Pepper Extract': 20,
    'Yellow Pepper Powder': 20,
    'Yellow Pepper Spice Mix': 20,
    'Yellow Peppers': 50,
    'Yellow Rice': 50,
    'Yellow Rice Extract': 20,
    'Yellow Rice Powder': 20,
    'Yellow Rice Spice Mix': 20,
    'Yellow Rock Sugar': 50,
    'Yellow Split Peas': 20,
    'Yellow Split Peas Extract': 20,
    'Yellow Split Peas Powder': 20,
    'Yellow Split Peas Spice Mix': 20,
    'Yellow Squash': 50,
    'Yellow Summer Squash': 50,
    'Yellow Tomato': 50,
    'Zucchini': 20,
    'Zucchini Extract': 20,
    'Zucchini Powder': 20,
    'Zucchini Spice Mix': 20,
  };
  static List<String> get allIngredientsList =>
      ingredientPopularityMap.keys.toList();

  static const List<String> units = [
    'cup',
    'cups',
    'tbsp',
    'tsp',
    'oz',
    'lb',
    'g',
    'kg',
    'ml',
    'L',
    'pinch',
    'dash',
    'to taste',
    'whole',
    'large',
    'medium',
    'small',
    'clove',
    'cloves',
    'slice',
    'slices',
    'can',
    'package',
    'bunch',
  ];

  static void addIngredient(String ingredient) {
    // Can't add to const map at runtime, but you could maintain a separate
    // user-added list if needed
  }

  // NEW: Get top N ingredients sorted by popularity
  static List<String> getTopIngredients(int count) {
    final sorted = ingredientPopularityMap.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    return sorted.take(count).map((e) => e.key).toList();
  }

  // Inside your IngredientData class (or wherever your search function is)

  static List<String> searchIngredients(String query, {int limit = 10}) {
    if (query.isEmpty) {
      return getTopIngredients(limit); // Fallback for empty query
    }

    final lowerQuery = query.toLowerCase();

    // REGEX EXPLANATION:
    // (\s|^): Matches a whitespace character (\s) OR the start of the string (^)
    // (?!\s): Negative lookahead to ensure we don't match a whitespace character itself
    // : We ensure the next characters match the start of the query
    final regex = RegExp(r'(\s|^)' + lowerQuery, caseSensitive: false);

    return IngredientData.allIngredientsList
        .where(
          (ingredient) =>
              // We check the ingredient itself (for start-of-string match)
              // OR if the regex finds a word-boundary match.
              ingredient.toLowerCase().startsWith(lowerQuery) ||
              regex.hasMatch(ingredient.toLowerCase()),
        )
        .take(limit)
        .toList();
  }
}
