class IngredientData {
  static List<String> ingredients = [
    'All-Purpose Flour',
    'Bread Flour',
    'Cake Flour',
    'Whole Wheat Flour',
    'Sugar',
    'Brown Sugar',
    'Powdered Sugar',
    'Salt',
    'Black Pepper',
    'Butter',
    'Unsalted Butter',
    'Eggs',
    'Egg Whites',
    'Egg Yolks',
    'Milk',
    'Heavy Cream',
    'Sour Cream',
    'Olive Oil',
    'Vegetable Oil',
    'Garlic',
    'Garlic Powder',
    'Onion',
    'Onion Powder',
    'Tomatoes',
    'Tomato Paste',
    'Chicken Breast',
    'Ground Beef',
    'Bacon',
    'Pasta',
    'Spaghetti',
    'Penne',
    'Rice',
    'Parmesan Cheese',
    'Mozzarella Cheese',
    'Cheddar Cheese',
    'Basil',
    'Oregano',
    'Thyme',
    'Parsley',
    'Paprika',
    'Cumin',
    'Chili Powder',
    'Vanilla Extract',
    'Baking Powder',
    'Baking Soda',
    'Yeast',
    'Honey',
    'Lemon',
    'Lime',
  ];

  static const List<String> units = [
    'cup',
    'cups',
    'tbsp',
    'tsp',
    'oz',
    'lb',
    'g',
    'kg',
    'ml',
    'L',
    'pinch',
    'dash',
    'to taste',
    'whole',
    'large',
    'medium',
    'small',
    'clove',
    'cloves',
    'slice',
    'slices',
    'can',
    'package',
    'bunch',
  ];

  static void addIngredient(String ingredient) {
    if (!ingredients.contains(ingredient)) {
      ingredients.add(ingredient);
      ingredients.sort();
    }
  }
}
